### ISSUE TITLE
Extension stopped working

### ISSUE THREAD

**Issue by fedorinoGore** [TimonVS/vscode-react-standard#1]
For some reason, not sure, but maybe following latest VS Code updates, the snippets just stopped working... Cannot see them while typing...
VS Code 1.9.1
OS X 10.12.3
Node 6.5.9

**Comment by TimonVS** [comment]
I'm sorry, I'm just seeing this issue now. It's working fine for me (same version of VS Code and macOS). What other extensions are you using?

**Comment by TimonVS** [comment]
I published a new version, let me know if it's working again :).

**Comment by Ciwan1859** [comment]
Not working for me either. I'm on VS Code version `1.13.1` on Windows 10. I also made sure that the language set on the file is JavaScript React, but still nothing.

**Comment by Ciwan1859** [comment]
Never mind. I came into work this morning and it works! Perhaps laptop needed restarting. Thanks for the extension.

**Comment by TimonVS** [comment]
@Ciwan1859 No problem. I have actually not updated this plugin in a while because I have no need for it anymore. That's why I have decided to deprecate the plugin, please refer to the readme for a detailed description on how to migrate to alternatives (https://github.com/TimonVS/vscode-react-standard/blob/master/README.md).
