### ISSUE TITLE
.vscode/extensions/TimonVS.ReactSnippetsStandard-1.1.0]: Unknown language in `contributes.snippets.language`. Provided value: jsx

### ISSUE THREAD

**Issue by capaj** [TimonVS/vscode-react-standard#2]
I get this when I run my vscode. I don't think jsx is a language in vscode.

**Comment by TimonVS** [comment]
Do you always get this when you open VS Code? Or did you just get this error once?

**Comment by hasssan** [comment]
please update marketplace version, I always got this error

thanks

![screen shot 2017-03-23 at 1 55 14 am](https://cloud.githubusercontent.com/assets/239714/24215644/fa5f5b0a-0f6b-11e7-8a6a-664d6c5fe716.jpg)

**Comment by TimonVS** [comment]
I will publish a new version once I'm back from my holiday :)

**Comment by capaj** [comment]
@TimonVS still waiting for you to publish a new version.

**Comment by capaj** [comment]
@TimonVS I am taking your snippets and putting them into my standard.js snippets package. Waiting 2 months for a publish? Unacceptable.

**Comment by TimonVS** [comment]
@capaj I have actually not updated this plugin in a while because I have no need for it anymore. That's why I have decided to deprecate the plugin, please refer to the readme for a detailed description on how to migrate to alternatives (https://github.com/TimonVS/vscode-react-standard/blob/master/README.md).
